
package pions.view;

import javax.swing.JOptionPane;
import pions.controller.ContactIterator;
import pions.controller.Contacts;

/**
 *
 * @author George
 */
public class ContactList extends AbstractList {

    /** Creates new form Contacts */
    public ContactList(ContactIterator iter) {
        initComponents();

        super.panel_display = panel_display;
        super.set(iter);
    }

    @Override
    public void setEnabled(boolean enabled){
        button_select_all.setEnabled(enabled);
        button_select_none.setEnabled(enabled);
        scrollpane_display.setEnabled(enabled);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_title = new javax.swing.JLabel();
        label_directions = new javax.swing.JLabel();
        button_select_all = new javax.swing.JButton();
        label_select = new javax.swing.JLabel();
        button_select_none = new javax.swing.JButton();
        scrollpane_display = new javax.swing.JScrollPane();
        panel_display = new javax.swing.JPanel();
        button_sendalert = new javax.swing.JToggleButton();
        button_contactrequest = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(300, 400));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pions.PIONS.class).getContext().getResourceMap(ContactList.class);
        label_title.setFont(resourceMap.getFont("label_title.font")); // NOI18N
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText(resourceMap.getString("label_title.text")); // NOI18N
        label_title.setName("label_title"); // NOI18N

        label_directions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_directions.setText(resourceMap.getString("label_directions.text")); // NOI18N
        label_directions.setName("label_directions"); // NOI18N

        button_select_all.setText(resourceMap.getString("button_select_all.text")); // NOI18N
        button_select_all.setName("button_select_all"); // NOI18N
        button_select_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_select_allActionPerformed(evt);
            }
        });

        label_select.setText(resourceMap.getString("label_select.text")); // NOI18N
        label_select.setName("label_select"); // NOI18N

        button_select_none.setText(resourceMap.getString("button_select_none.text")); // NOI18N
        button_select_none.setName("button_select_none"); // NOI18N
        button_select_none.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_select_noneActionPerformed(evt);
            }
        });

        scrollpane_display.setName("scrollpane_display"); // NOI18N

        panel_display.setName("panel_display"); // NOI18N

        javax.swing.GroupLayout panel_displayLayout = new javax.swing.GroupLayout(panel_display);
        panel_display.setLayout(panel_displayLayout);
        panel_displayLayout.setHorizontalGroup(
            panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        panel_displayLayout.setVerticalGroup(
            panel_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        scrollpane_display.setViewportView(panel_display);

        button_sendalert.setText(resourceMap.getString("button_sendalert.text")); // NOI18N
        button_sendalert.setName("button_sendalert"); // NOI18N
        button_sendalert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sendalertActionPerformed(evt);
            }
        });

        button_contactrequest.setText(resourceMap.getString("button_contactrequest.text")); // NOI18N
        button_contactrequest.setName("button_contactrequest"); // NOI18N
        button_contactrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_contactrequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_directions, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_sendalert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_contactrequest)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_select)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_select_all)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_select_none)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpane_display, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_directions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_sendalert)
                    .addComponent(button_contactrequest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_select)
                    .addComponent(button_select_all)
                    .addComponent(button_select_none))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpane_display, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_select_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_select_allActionPerformed
        super.selectAll();
    }//GEN-LAST:event_button_select_allActionPerformed

    private void button_select_noneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_select_noneActionPerformed
        super.selectNone();
    }//GEN-LAST:event_button_select_noneActionPerformed

    private void button_sendalertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sendalertActionPerformed
        if(button_sendalert.isSelected()){
            PIONSView.getInstance().setAux(new SendAlert(super.getIndices()));
            this.setEnabled(false);
        }
        else{
            PIONSView.getInstance().resetAux();
            this.setEnabled(true);
        }
    }//GEN-LAST:event_button_sendalertActionPerformed

    private void button_contactrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_contactrequestActionPerformed
        String gmail = "";

        while(gmail.equals("")){
            gmail = JOptionPane.showInputDialog(this,
                "Enter contact's Gmail address.\nRemember to include the @gmail.com suffix.",
                "Send Contact Request",
                JOptionPane.OK_CANCEL_OPTION);
        }

        if(gmail != null) Contacts.sendContactRequest(gmail);
    }//GEN-LAST:event_button_contactrequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_contactrequest;
    private javax.swing.JButton button_select_all;
    private javax.swing.JButton button_select_none;
    private javax.swing.JToggleButton button_sendalert;
    private javax.swing.JLabel label_directions;
    private javax.swing.JLabel label_select;
    private javax.swing.JLabel label_title;
    private javax.swing.JPanel panel_display;
    private javax.swing.JScrollPane scrollpane_display;
    // End of variables declaration//GEN-END:variables

}
