
package pions.view.alerts;

import pions.controller.Alerts;

/**
 *
 * 
 */
public class UpdateAlerts extends javax.swing.JPanel {

    private Thread update_thread = null;

    /** Creates new form RetrieveAlerts */
    public UpdateAlerts() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_title = new javax.swing.JLabel();
        label_directions = new javax.swing.JLabel();
        scrollpane_errors = new javax.swing.JScrollPane();
        textarea_errors = new javax.swing.JTextArea();
        togglebutton_update = new javax.swing.JToggleButton();
        label_errors = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(300, 400));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pions.PIONS.class).getContext().getResourceMap(UpdateAlerts.class);
        label_title.setFont(resourceMap.getFont("label_title.font")); // NOI18N
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText(resourceMap.getString("label_title.text")); // NOI18N
        label_title.setName("label_title"); // NOI18N

        label_directions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_directions.setText(resourceMap.getString("label_directions.text")); // NOI18N
        label_directions.setName("label_directions"); // NOI18N

        scrollpane_errors.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpane_errors.setName("scrollpane_errors"); // NOI18N

        textarea_errors.setBackground(getBackground());
        textarea_errors.setColumns(20);
        textarea_errors.setEditable(false);
        textarea_errors.setLineWrap(true);
        textarea_errors.setRows(5);
        textarea_errors.setWrapStyleWord(true);
        textarea_errors.setName("textarea_errors"); // NOI18N
        scrollpane_errors.setViewportView(textarea_errors);

        togglebutton_update.setText(resourceMap.getString("togglebutton_update.text")); // NOI18N
        togglebutton_update.setName("togglebutton_update"); // NOI18N
        togglebutton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglebutton_updateActionPerformed(evt);
            }
        });

        label_errors.setText(resourceMap.getString("label_errors.text")); // NOI18N
        label_errors.setName("label_errors"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(label_directions, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(togglebutton_update, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_errors, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpane_errors, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_directions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(togglebutton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_errors)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpane_errors, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void togglebutton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglebutton_updateActionPerformed
        if(togglebutton_update.isSelected()){
            textarea_errors.setText("");
            update_thread = new UpdateThread();
            update_thread.start();
        }
        else{
            update_thread.interrupt();
        }
    }//GEN-LAST:event_togglebutton_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_directions;
    private javax.swing.JLabel label_errors;
    private javax.swing.JLabel label_title;
    private javax.swing.JScrollPane scrollpane_errors;
    private javax.swing.JTextArea textarea_errors;
    private javax.swing.JToggleButton togglebutton_update;
    // End of variables declaration//GEN-END:variables


    //TODO implement extends SwingWorker
    private class UpdateThread extends Thread {
        @Override
        public void interrupt(){
            togglebutton_update.setText(org.jdesktop.application.Application.getInstance(pions.PIONS.class).getContext().getResourceMap(UpdateAlerts.class).getString("togglebutton_update.text"));
            super.interrupt();
        }

        @Override
        public void run() {
            togglebutton_update.setText("Updating Alerts... (click here to stop)");
            
            for(String exception: Alerts.parseAlerts()){
                textarea_errors.setText(textarea_errors.getText() + exception + "\n" + "\n");
            }

            togglebutton_update.setSelected(false);
            interrupt();
        }
    }
}
