
package pions.view;

import javax.swing.JPanel;
import org.w3c.dom.Document;
import pions.controller.AlertXMLIterator;

/**
 *
 * @author George
 */
public class ActiveAlerts extends JPanel {

    private AlertXMLIterator iter = null;

    /** Creates new form NewAlerts */
    public ActiveAlerts() {
        initComponents();
    }

    public void set(AlertXMLIterator iter){
        this.iter = iter;

        StringBuffer buffer = new StringBuffer();

        while(iter.hasNext()){
            Document xml = iter.next();

            buffer.append("Sender: \n");
            buffer.append(xml.getElementById(AlertXMLIterator.SENDER).getNodeValue());

            buffer.append("Type: \n");
            buffer.append(xml.getElementById(AlertXMLIterator.TYPE).getNodeValue());

            buffer.append("Description: \n");
            buffer.append(xml.getElementById(AlertXMLIterator.DESCRIPTION).getNodeValue());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display_area = new javax.swing.JScrollPane();
        label_title = new javax.swing.JLabel();
        label_directions = new javax.swing.JLabel();
        button_accept = new javax.swing.JButton();
        button_reject = new javax.swing.JButton();
        button_ignore = new javax.swing.JButton();
        button_select_all = new javax.swing.JButton();
        button_select_none = new javax.swing.JButton();
        label_select = new javax.swing.JLabel();
        button_view = new javax.swing.JButton();

        setName("Form"); // NOI18N

        display_area.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        display_area.setName("display_area"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pions.PIONS.class).getContext().getResourceMap(ActiveAlerts.class);
        label_title.setFont(resourceMap.getFont("label_title.font")); // NOI18N
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText(resourceMap.getString("label_title.text")); // NOI18N
        label_title.setName("label_title"); // NOI18N

        label_directions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_directions.setText(resourceMap.getString("label_directions.text")); // NOI18N
        label_directions.setName("label_directions"); // NOI18N

        button_accept.setText(resourceMap.getString("button_accept.text")); // NOI18N
        button_accept.setName("button_accept"); // NOI18N

        button_reject.setText(resourceMap.getString("button_reject.text")); // NOI18N
        button_reject.setName("button_reject"); // NOI18N

        button_ignore.setText(resourceMap.getString("button_ignore.text")); // NOI18N
        button_ignore.setName("button_ignore"); // NOI18N

        button_select_all.setText(resourceMap.getString("button_select_all.text")); // NOI18N
        button_select_all.setName("button_select_all"); // NOI18N

        button_select_none.setText(resourceMap.getString("button_select_none.text")); // NOI18N
        button_select_none.setName("button_select_none"); // NOI18N

        label_select.setText(resourceMap.getString("label_select.text")); // NOI18N
        label_select.setName("label_select"); // NOI18N

        button_view.setText(resourceMap.getString("button_view.text")); // NOI18N
        button_view.setName("button_view"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_directions, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_select)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_select_all)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_select_none))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_view)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_accept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_reject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_ignore)))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display_area, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_directions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_view)
                    .addComponent(button_accept)
                    .addComponent(button_reject)
                    .addComponent(button_ignore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_select)
                    .addComponent(button_select_all)
                    .addComponent(button_select_none))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(display_area, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_accept;
    private javax.swing.JButton button_ignore;
    private javax.swing.JButton button_reject;
    private javax.swing.JButton button_select_all;
    private javax.swing.JButton button_select_none;
    private javax.swing.JButton button_view;
    private javax.swing.JScrollPane display_area;
    private javax.swing.JLabel label_directions;
    private javax.swing.JLabel label_select;
    private javax.swing.JLabel label_title;
    // End of variables declaration//GEN-END:variables

}
